### ISSUE TITLE
Datalek?

### ISSUE THREAD

**Issue by JanKanis** [Amsterdam/iiif-metadata-server#76]
LS,

Volgens de beschrijving op [data.amsterdam.nl](https://api.data.amsterdam.nl/api/) is deze api alleen bereikbaar binnen de gemeente. Echter als ik naar een url zoals https://api.data.amsterdam.nl/iiif-metadata/bouwdossier/ ga krijg ik allerlei metadata over heel veel bouwdossiers te zien. Ik woon niet in Amsterdam en ik werk ook niet voor de gemeente of zoiets. Klopt dit?

**Comment by kramer65** [comment]
Hoi @JanKanis 

Leuk dat je ons werk bekijkt en mooi dat je security een warm hart toe draagt.

De manier waarop je het ziet werken is echter volledig intentioneel; alle metadata voor alle bestanden is volledig openbaar. Dus als je daar in wil grasduinen; ga je gang. De toegang tot de bestanden zelf heeft wél bepaalde restricties. En mocht je daar een lek in vinden dan horen we dat natuurlijk heel graag.
